//! Compiled rule graph and grammar registry.
//!
//! Grammars are parsed lazily on first use and compiled into a flat rule
//! arena (`Vec<Rule>`); regexes inside rules compile lazily on first match
//! attempt. Cross-grammar includes (`source.js`, `text.html.basic#tag`) are
//! resolved eagerly at compile time so tokenization never needs mutable
//! access to the registry.

use std::cell::RefCell;
use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use anyhow::{anyhow, Result};

use super::raw::{RawGrammar, RawRule};
use super::regex::RegexSrc;

// Generated by build.rs: (language id, root scope name, zstd-compressed
// grammar JSON).
include!(concat!(env!("OUT_DIR"), "/grammar_data.rs"));

/// Decompresses an embedded grammar. The result is transient: it is parsed
/// into a [`RawGrammar`] and dropped, so only the compressed bytes and the
/// parsed tree stay resident.
pub(crate) fn decompress_grammar(compressed: &[u8]) -> Result<Vec<u8>> {
    use std::io::Read;
    let mut decoder = ruzstd::decoding::StreamingDecoder::new(compressed)
        .map_err(|e| anyhow!("invalid zstd frame: {e}"))?;
    let mut json = Vec::new();
    decoder.read_to_end(&mut json)?;
    Ok(json)
}

pub type RuleId = usize;

/// Scope name that may contain `$1` / `${1:/downcase}` capture references.
#[derive(Debug)]
pub struct ScopeName {
    pub raw: String,
    pub needs_substitution: bool,
}

impl ScopeName {
    fn new(raw: &str) -> Self {
        ScopeName {
            raw: raw.to_string(),
            needs_substitution: raw.contains('$'),
        }
    }
}

#[derive(Debug)]
pub struct CaptureDef {
    pub name: Option<ScopeName>,
    /// Set when the capture carries nested `patterns`; the captured text is
    /// re-tokenized with this rule.
    pub rule: Option<RuleId>,
}

#[derive(Debug)]
pub struct MatchRule {
    pub regex: Arc<RegexSrc>,
    pub name: Option<ScopeName>,
    pub captures: Vec<Option<CaptureDef>>,
}

#[derive(Debug)]
pub struct BeginEndRule {
    pub begin: Arc<RegexSrc>,
    pub begin_captures: Vec<Option<CaptureDef>>,
    pub end_source: String,
    /// Pre-built end regex when the pattern has no `\1` backreferences into
    /// the begin match; otherwise resolved per stack frame.
    pub end: Option<Arc<RegexSrc>>,
    pub end_has_back_references: bool,
    pub end_captures: Vec<Option<CaptureDef>>,
    pub name: Option<ScopeName>,
    pub content_name: Option<ScopeName>,
    pub patterns: Vec<RuleId>,
    pub apply_end_pattern_last: bool,
}

#[derive(Debug)]
pub struct BeginWhileRule {
    pub begin: Arc<RegexSrc>,
    pub begin_captures: Vec<Option<CaptureDef>>,
    pub while_source: String,
    pub while_: Option<Arc<RegexSrc>>,
    pub while_has_back_references: bool,
    pub while_captures: Vec<Option<CaptureDef>>,
    pub name: Option<ScopeName>,
    pub content_name: Option<ScopeName>,
    pub patterns: Vec<RuleId>,
}

#[derive(Debug)]
pub enum Rule {
    /// Placeholder / disabled / unresolvable rule. Never matches.
    None,
    /// Pattern container: grammar roots, repository entries that only carry
    /// `patterns`, and capture-retokenization rules.
    Include { patterns: Vec<RuleId> },
    Match(MatchRule),
    BeginEnd(BeginEndRule),
    BeginWhile(BeginWhileRule),
}

struct GrammarState {
    raw: &'static RawGrammar,
    root: RuleId,
    /// RawRule pointer (as usize) -> compiled rule id, for cycle breaking.
    compiled: HashMap<usize, RuleId>,
}

#[derive(Default)]
pub struct Registry {
    rules: Vec<Rule>,
    /// Root scope name -> grammar.
    grammars: HashMap<String, GrammarState>,
    /// Flattened candidate lists, built lazily during tokenization.
    flat_cache: RefCell<HashMap<RuleId, Arc<[RuleId]>>>,
}

impl Registry {
    pub fn rule(&self, id: RuleId) -> &Rule {
        &self.rules[id]
    }

    pub fn language_ids() -> Vec<String> {
        RAW_GRAMMARS.iter().map(|(id, _, _)| id.to_string()).collect()
    }

    /// Loads (if needed) the grammar for a language id and returns
    /// `(root scope name, root rule id)`.
    pub fn grammar_for_language(&mut self, language: &str) -> Result<(String, RuleId)> {
        let (_, scope, _) = RAW_GRAMMARS
            .iter()
            .find(|(id, _, _)| *id == language)
            .ok_or_else(|| anyhow!("unsupported language: {language}"))?;
        let scope = scope.to_string();
        let root = self
            .grammar_for_scope(&scope)
            .ok_or_else(|| anyhow!("failed to load grammar for {language}"))?;
        Ok((scope, root))
    }

    /// Loads (if needed) the grammar with the given root scope name and
    /// returns its root rule. Returns `None` for unknown scopes (a grammar
    /// referencing a language we don't bundle).
    fn grammar_for_scope(&mut self, scope: &str) -> Option<RuleId> {
        if let Some(g) = self.grammars.get(scope) {
            return Some(g.root);
        }
        let (_, _, compressed) = RAW_GRAMMARS.iter().find(|(_, s, _)| *s == scope)?;
        let json = decompress_grammar(compressed).ok()?;
        let raw: RawGrammar = match serde_json::from_slice(&json) {
            Ok(g) => g,
            Err(_) => return None,
        };
        // Grammars are cached for the process lifetime; leaking gives us
        // 'static references so compiled rules can point into the raw tree.
        let raw: &'static RawGrammar = Box::leak(Box::new(raw));

        // Register the root before compiling so recursive includes
        // (grammar cycles like html <-> javascript) resolve to it.
        let root = self.alloc(Rule::None);
        self.grammars.insert(
            scope.to_string(),
            GrammarState { raw, root, compiled: HashMap::new() },
        );

        let mut repos = Vec::new();
        if let Some(repo) = &raw.repository {
            repos.push(repo);
        }
        let patterns = self.compile_patterns(scope, root, &repos, &raw.patterns);
        self.rules[root] = Rule::Include { patterns };
        Some(root)
    }

    fn alloc(&mut self, rule: Rule) -> RuleId {
        self.rules.push(rule);
        self.rules.len() - 1
    }

    fn compile_patterns(
        &mut self,
        scope: &str,
        self_id: RuleId,
        repos: &[&'static HashMap<String, RawRule>],
        raw_rules: &'static [RawRule],
    ) -> Vec<RuleId> {
        raw_rules
            .iter()
            .filter_map(|r| self.compile_rule(scope, self_id, repos, r))
            .collect()
    }

    fn compile_rule(
        &mut self,
        scope: &str,
        self_id: RuleId,
        repos: &[&'static HashMap<String, RawRule>],
        raw: &'static RawRule,
    ) -> Option<RuleId> {
        if raw.disabled {
            return None;
        }

        // Includes are references, not new rules.
        if let Some(include) = &raw.include {
            return self.compile_include(scope, self_id, repos, include);
        }

        let key = raw as *const RawRule as usize;
        if let Some(&id) = self.grammars[scope].compiled.get(&key) {
            return Some(id);
        }
        // Reserve the id before compiling the body so self-referencing
        // repository entries terminate.
        let id = self.alloc(Rule::None);
        self.grammars.get_mut(scope).unwrap().compiled.insert(key, id);

        // A rule-local repository shadows outer entries for its subtree.
        let mut repos: Vec<&'static HashMap<String, RawRule>> = repos.to_vec();
        if let Some(repo) = &raw.repository {
            repos.push(repo);
        }

        let rule = if let Some(begin) = &raw.begin {
            let patterns = match &raw.patterns {
                Some(p) => self.compile_patterns(scope, self_id, &repos, p),
                None => Vec::new(),
            };
            if let Some(while_src) = &raw.while_ {
                let has_backrefs = RegexSrc::has_back_references(while_src);
                Rule::BeginWhile(BeginWhileRule {
                    begin: Arc::new(RegexSrc::new(begin)),
                    begin_captures: self.compile_captures(
                        scope, self_id, &repos, raw.effective_begin_captures()),
                    while_source: while_src.clone(),
                    while_: (!has_backrefs).then(|| Arc::new(RegexSrc::new(while_src))),
                    while_has_back_references: has_backrefs,
                    while_captures: self.compile_captures(
                        scope, self_id, &repos, raw.effective_while_captures()),
                    name: raw.name.as_deref().map(ScopeName::new),
                    content_name: raw.content_name.as_deref().map(ScopeName::new),
                    patterns,
                })
            } else {
                // A begin rule without an end extends to the end of the
                // document (vscode-textmate uses a never-matching end too).
                let end_source = raw.end.clone().unwrap_or_else(|| "\u{FFFF}".to_string());
                let has_backrefs = RegexSrc::has_back_references(&end_source);
                Rule::BeginEnd(BeginEndRule {
                    begin: Arc::new(RegexSrc::new(begin)),
                    begin_captures: self.compile_captures(
                        scope, self_id, &repos, raw.effective_begin_captures()),
                    end: (!has_backrefs).then(|| Arc::new(RegexSrc::new(&end_source))),
                    end_source,
                    end_has_back_references: has_backrefs,
                    end_captures: self.compile_captures(
                        scope, self_id, &repos, raw.effective_end_captures()),
                    name: raw.name.as_deref().map(ScopeName::new),
                    content_name: raw.content_name.as_deref().map(ScopeName::new),
                    patterns,
                    apply_end_pattern_last: raw.apply_end_pattern_last,
                })
            }
        } else if let Some(match_src) = &raw.match_ {
            Rule::Match(MatchRule {
                regex: Arc::new(RegexSrc::new(match_src)),
                name: raw.name.as_deref().map(ScopeName::new),
                captures: self.compile_captures(scope, self_id, &repos, raw.captures.as_ref()),
            })
        } else if let Some(patterns) = &raw.patterns {
            let patterns = self.compile_patterns(scope, self_id, &repos, patterns);
            Rule::Include { patterns }
        } else {
            Rule::None
        };

        self.rules[id] = rule;
        Some(id)
    }

    fn compile_include(
        &mut self,
        scope: &str,
        self_id: RuleId,
        repos: &[&'static HashMap<String, RawRule>],
        include: &str,
    ) -> Option<RuleId> {
        match include {
            // `$base` should be the outermost grammar when embedded; we
            // approximate it with the current grammar's root.
            "$self" | "$base" => Some(self_id),
            _ if include.starts_with('#') => {
                let name = &include[1..];
                let target = repos.iter().rev().find_map(|r| r.get(name))?;
                self.compile_rule(scope, self_id, repos, target)
            }
            _ => {
                // External grammar: `source.js` or `text.html.basic#frag`.
                let (ext_scope, fragment) = match include.split_once('#') {
                    Some((s, f)) => (s, Some(f)),
                    None => (include, None),
                };
                let ext_scope = if ext_scope.is_empty() { scope } else { ext_scope };
                let ext_root = self.grammar_for_scope(ext_scope)?;
                match fragment {
                    None => Some(ext_root),
                    Some(frag) => {
                        let g = &self.grammars[ext_scope];
                        let raw = g.raw;
                        let target = raw.repository.as_ref()?.get(frag)?;
                        let mut ext_repos = Vec::new();
                        if let Some(repo) = &raw.repository {
                            ext_repos.push(repo);
                        }
                        self.compile_rule(ext_scope, ext_root, &ext_repos, target)
                    }
                }
            }
        }
    }

    fn compile_captures(
        &mut self,
        scope: &str,
        self_id: RuleId,
        repos: &[&'static HashMap<String, RawRule>],
        captures: Option<&'static HashMap<String, RawRule>>,
    ) -> Vec<Option<CaptureDef>> {
        let Some(captures) = captures else {
            return Vec::new();
        };
        let mut max_index = 0usize;
        let mut parsed: Vec<(usize, &'static RawRule)> = Vec::with_capacity(captures.len());
        for (key, value) in captures {
            // Keys are capture group indices; named-group keys are ignored.
            if let Ok(index) = key.parse::<usize>() {
                max_index = max_index.max(index);
                parsed.push((index, value));
            }
        }
        let mut out: Vec<Option<CaptureDef>> = (0..=max_index).map(|_| None).collect();
        for (index, value) in parsed {
            let rule = value.patterns.as_ref().map(|patterns| {
                let patterns = self.compile_patterns(scope, self_id, repos, patterns);
                self.alloc(Rule::Include { patterns })
            });
            out[index] = Some(CaptureDef {
                name: value.name.as_deref().map(ScopeName::new),
                rule,
            });
        }
        out
    }

    /// Flattened match candidates for a rule's `patterns`: `Include`
    /// containers are expanded recursively (cycle-safe), leaving only
    /// Match / BeginEnd / BeginWhile rules in pattern order.
    pub fn candidates(&self, id: RuleId) -> Arc<[RuleId]> {
        if let Some(flat) = self.flat_cache.borrow().get(&id) {
            return flat.clone();
        }
        let mut out = Vec::new();
        let mut visited = HashSet::new();
        visited.insert(id);
        self.flatten_into(id, &mut out, &mut visited);
        let flat: Arc<[RuleId]> = out.into();
        self.flat_cache.borrow_mut().insert(id, flat.clone());
        flat
    }

    fn flatten_into(&self, id: RuleId, out: &mut Vec<RuleId>, visited: &mut HashSet<RuleId>) {
        let patterns = match &self.rules[id] {
            Rule::Include { patterns } => patterns,
            Rule::BeginEnd(r) => &r.patterns,
            Rule::BeginWhile(r) => &r.patterns,
            Rule::Match(_) | Rule::None => return,
        };
        for &p in patterns {
            match &self.rules[p] {
                Rule::Include { .. } => {
                    if visited.insert(p) {
                        self.flatten_into(p, out, visited);
                    }
                }
                Rule::None => {}
                _ => out.push(p),
            }
        }
    }
}
