// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Tokenizes `source` using the bundled TextMate grammar for `language`.
///
/// `language` must be a canonical grammar id (a file stem from
/// `assets/grammars`, e.g. `dart`, `cpp`); alias resolution (`py` -> `python`)
/// happens on the Dart side. Runs on a worker thread; grammars are compiled
/// lazily and cached for the process lifetime.
Future<List<Token>> tokenize({
  required String language,
  required String source,
}) => RustLib.instance.api.crateApiHighlighterTokenize(
  language: language,
  source: source,
);

/// Canonical ids of all bundled grammars.
List<String> supportedLanguages() =>
    RustLib.instance.api.crateApiHighlighterSupportedLanguages();

/// A run of source text with the TextMate scopes that apply to it.
///
/// Offsets are UTF-16 code units into the source string passed to
/// [`tokenize`], so they can be used directly as Dart string indices.
class Token {
  final int start;
  final int end;

  /// Scope stack, outermost first
  /// (e.g. `["source.dart", "string.interpolated.dart"]`).
  final List<String> scopes;

  const Token({
    required this.start,
    required this.end,
    required this.scopes,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ scopes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Token &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          scopes == other.scopes;
}
